### ISSUE TITLE
Audio is not optional

### ISSUE THREAD

**Issue by mdm508** [skozlovf/anki_deck#1]
Unless I doing something wrong, I believe that -a option is not actually optional. According to the read me audio should be optional. 

Inside the anki_deck foler is a .xdxf and word.txt list.

The command I used is show below along with the corresponding error produced.

```
/usr/local/bin/python3.7 /Users/m/Programming/PythonProjects/anki_deck/anki_deck/cli.py -d dict.xdxf -w words.txt txt

Traceback (most recent call last):
  File "/Users/m/Programming/PythonProjects/anki_deck/anki_deck/cli.py", line 80, in <module>
    run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/m/Programming/PythonProjects/anki_deck/anki_deck/cli.py", line 54, in txt
    get_cards(ctx['words'], ctx['dict'], ctx['audio'], handler)
  File "/Users/m/Programming/PythonProjects/anki_deck/anki_deck/parser.py", line 182, in get_cards
    need_audio = op.exists(sound_path)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```
This line seems to indicate that audio is required. 

> File "/Users/m/Programming/PythonProjects/anki_deck/anki_deck/parser.py", line 182, in get_cards
>     need_audio = op.exists(sound_path)
>

**Comment by skozlovf** [comment]
Should work now. Feel free to reopen.
